### PR TITLE
Panic on missing _ghc and _gho tables

### PR DESCRIPTION
**Pull request by shlomi-noach**
Fixes https://github.com/github/gh-ost/issues/763

In case of accidental removal of `_gho` table while migration was running, `gh-ost` was correctly bailing out on failing to apply rows to the `_gho` table, but did not panic during cut-over phase.

With this PR:

- `gh-ost` correctly panics at cut-over phase
- Also, `gh-ost` now correctly panics when the `_ghc` table is accidentally removed throughout the migration.

cc @tomkrouper @ggunson

### CODE REVIEW

**Comment by shlomi-noach** [comment]
This seems too strict. We have a known race condition after cut-over where the `gho` table can be renamed; this PR then fails the migration even though everything is fine.

**Review by timvaillancourt — APPROVED** [review]

**Comment by shlomi-noach** [comment]
As per https://github.com/github/gh-ost/pull/772#issuecomment-518127278 I recommend holding off this PR.

**Comment by timvaillancourt** [comment]
> This seems too strict. We have a known race condition after cut-over where the `gho` table can be renamed; this PR then fails the migration even though everything is fine.

@shlomi-noach would this PR be safer if we had a mutex at the cut-over, eg: https://github.com/github/gh-ost/pull/755?

**Comment by shlomi-noach** [comment]
> would this PR be safer if we had a mutex at the cut-over

@timvaillancourt I guess maybe? Depends on the mutex; there's already much locking/scheduling in `gh-ost` so we'd need to be careful so as not to introduce a deadlock or any other mistake.

**Pull request closed without merging**
