### PR TITLE
Reduce minimum maxLagMillisecondsThrottleThreshold to 100ms

### PR DESCRIPTION
**Pull request by jonahberquist**
This PR reduces the minimum value for maxLagMillisecondsThrottleThreshold from 1000ms to 100ms per https://github.com/github/gh-ost/issues/203.

> In case this PR introduced Go code changes:

- [ ] contributed code is using same conventions as original code
- [ ] code is formatted via `gofmt` (please avoid `goimports`)
- [ ] code is built via `./build.sh`
- [ ] code is tested via `./test.sh`

### CODE REVIEW

**Comment by shlomi-noach** [comment]
As per https://github.com/github/gh-ost/issues/203#issuecomment-243053695 there's some development involved in this, I'm using this branch.

**Comment by jonahberquist** [comment]
👍 Feel free to use this branch

**Comment by shlomi-noach** [comment]
support for millisecond throttling

- `--max-lag-millis` is at least `100ms`
- `--heartbeat-interval-millis` introduced; defaults `500ms`, can range `100ms` - `1s`
- Control replicas lag calculated asynchronously to throttle test
  - aggressive when `max-lag-millis < 1000` and when `replication-lag-query` is given

**Comment by shlomi-noach** [comment]
Sent to testing

**Comment by shlomi-noach** [comment]
Passes testing

**Pull request merged**
