### PR TITLE
Enum to varchar

### PR DESCRIPTION
**Pull request by shlomi-noach**
Related issue: https://github.com/github/gh-ost/issues/642

### Description

Looking into `-alter` converting an `enum` into `varchar`. Per https://github.com/github/gh-ost/issues/642 this copies the numeric value of the enum into the varchar column, where we want the textual value.

Initial commit: test suite to confirm error.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Sorry, meant to open downstream: https://github.com/openark/gh-ost/pull/18

**Comment by timvaillancourt** [comment]
@shlomi-noach any concerns if I re-open this PR? I think this includes some PRs we haven't merged but this would be useful to have in this repo

**Comment by shlomi-noach** [comment]
@timvaillancourt let me open a new one, since there's been more commits to this branch than are present here.

**Comment by timvaillancourt** [comment]
@shlomi-noach oh, thanks a lot!

We can handle getting this PR in-sync if you'd like, I think we'll just need to merge a few dependant PRs to get this one mergeable. Totally up to you, thanks!

**Comment by shlomi-noach** [comment]
@timvaillancourt I see some merge conflicts locally, looks like I need to pull from upstream. Will do so tomorrow morning!

**Comment by timvaillancourt** [comment]
@shlomi-noach thanks a lot!

This suppot will unblock some `varchar` -> `enum` migrations we wanted to do but were afraid we couldn't roll back ❤️🎉

**Comment by shlomi-noach** [comment]
> unblock some varchar -> enum

I hope you mean `enum` -> `varchar` :stuck_out_tongue:

**Comment by timvaillancourt** [comment]
> > unblock some varchar -> enum
> 
> I hope you mean `enum` -> `varchar` 😛

@shlomi-noach I think the blocked migrations are `varchar` -> `enum` (which already worked?) but we were worried we couldn't reverse the migration without trashing the data if we needed to

I believe we would have numbers instead of real `varchar` values if we reversed a migration to `enum`

**Comment by shlomi-noach** [comment]
ahh, got it.

**Comment by shlomi-noach** [comment]
branch updated after recent merge of downstream contribution.

**Comment by timvaillancourt** [comment]
This PR passed integration testing 100%, merging. Thanks @shlomi-noach!

**Pull request merged**
