### PR TITLE
avoid to send drop cutover sentry table to mysql twice v2

### PR DESCRIPTION
**Pull request by MOON-CLJ**
this pr is another way to deal with issue: #737 

the first two commits are the same as https://github.com/github/gh-ost/pull/743 ，instead use get_lock，this pr use tableUnlocked channel to sync。

### CODE REVIEW

**Comment by MOON-CLJ** [comment]
@shlomi-noach yes, you're right。 

can we just delete the logic "defer this.DropAtomicCutOverSentryTableIfExists()"? because a successful cutover will drop the sentry table eventually。or do you have any other idea? 

ps, even this bug is even more a MTS's bug，i am thinking what can we do in gh-ost to eliminate the pain。

**Comment by shlomi-noach** [comment]
OK, a less-pretty and yet simple solution is to protect the dropping of the table by a mutex, and always skip the 2nd operation. It is imperative that the table is dropped no matter what, which is why the `defer DropAtomicCutOverSentryTableIfExists()` is there.

**Comment by MOON-CLJ** [comment]
@shlomi-noach "to protect the dropping of the table by a mute", yes, can i gave another pr for this?

**Comment by shlomi-noach** [comment]
@MOON-CLJ sure, thank you!

**Pull request closed without merging**
