### PR TITLE
Discard foreign keys

### PR DESCRIPTION
**Pull request by shlomi-noach**
Storyline: https://github.com/github/gh-ost/issues/262

This PR supports dropping of foreign keys from a table. There's nothing special about what `gh-ost` does to make that happen: it just doesn't do anything to _create_ those foreign keys on the _ghost_ table.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `./test.sh`

### CODE REVIEW

**Comment by ggunson** [comment]
Can the docs say something as well about what it does to foreign keys that reference the migrated table? Even if that is repeating itself, that would be a good place to repeat it.

**Comment by shlomi-noach** [comment]
@ggunson thanks for your comment, and I realize we need to refine this and only allow on tables with child-side FK. I don't wish to support any kind of parent-size FK handling at this time; it seems too dangerous to me (`_del` table dropped with `on delete cascade` --> whoops, all rows deleted from child table)

**Comment by shlomi-noach** [comment]
@ggunson https://github.com/github/gh-ost/pull/264/commits/a4d566e71c5bdfc6cb7dddf8f35e27581844fe27 takes care of parent-side: not supported. Only child-side foreign keys can be discarded.

For people who are looking to compleltely eliminate foreign keys on their database, you should begin with child-most tables and move upwards.

I don't have an immediate solution to a self-referencing FK table.

**Comment by ggunson** [comment]
> thanks for your comment, and I realize we need to refine this and only allow on tables with child-side FK.

@shlomi-noach I asked if the **docs** for this could say something about foreign keys referencing the table. So it was a suggestion that you add that to the docs you edited for this PR (e.g., the new flag description), that this doesn't apply to tables who are referenced in FKs from other tables.

**Comment by shlomi-noach** [comment]
@ggunson I was sure I did 😮 but then I realize I wrote this on another couple places. Will add.

Anyway, my original comment acknowledged that regardless of the docs, the _code_ was wrong, and that is fixed. Proper error messages will indicate the limitation where someone tried to drop a parent-side foreign key. Docs were supposed to follow suit...

**Pull request merged**
