### PR TITLE
Print status to migrationContext logger

### PR DESCRIPTION
**Pull request by SocalNick**
Related issue: https://github.com/github/gh-ost/issues/1026

### Description

Status is currently only sent to stdout. We'd like the status to also be sent to the migrationContext logger.

> In case this PR introduced Go code changes:

- [x] contributed code is using same conventions as original code
- [x] `script/cibuild` returns with no formatting errors, build errors or unit test errors.

### CODE REVIEW

**Comment by SocalNick** [comment]
cc @abeyum

**Review by Reynolds251 — APPROVED** [review]

**Review by Reynolds251 — APPROVED** [review]

**Comment by SocalNick** [comment]
Any chance someone could take a look and consider this PR? Thanks!

**Comment by timvaillancourt** [comment]
@SocalNick could you provide a before/after example of logging from this PR? Feel free to redact any sensitive info

Assuming this changes the logging output is there a way this change could be opt-in for backwards compatibility?

**Comment by SocalNick** [comment]
Hey @timvaillancourt - apologies, I missed your comment in January.

This was actually a miss from [when we contributed to logging interface in 2019/20](https://github.com/github/gh-ost/pull/789).

Before this change, the lines below with `msg="Copy` would only be sent to `stdout`. This change ensures the migration status lines are also printed to the configured migration context logger.

```
time="2022-03-15T11:46:51Z" level=info msg="Exact number of rows via COUNT: 200" migration=b6244fb7-7b39-48f4-a54c-d6cd83bc2d18

time="2022-03-15T11:46:51Z" level=info msg="First throttle metrics collected" migration=b6244fb7-7b39-48f4-a54c-d6cd83bc2d18

time="2022-03-15T11:46:51Z" level=info msg="Copy: 0/200 0.0%!;(MISSING) Applied: 0; Backlog: 0/1000; Time: 0s(total), 0s(copy); streamer: mysql-bin-changelog.000031:16847320; Lag: 0.02s, State: migrating; ETA: N/A" migration=b6244fb7-7b39-48f4-a54c-d6cd83bc2d18

time="2022-03-15T11:46:52Z" level=info msg="Copy: 0/200 0.0%!;(MISSING) Applied: 0; Backlog: 0/1000; Time: 1s(total), 1s(copy); streamer: mysql-bin-changelog.000031:16848554; Lag: 0.01s, State: migrating; ETA: N/A" migration=b6244fb7-7b39-48f4-a54c-d6cd83bc2d18

time="2022-03-15T11:46:52Z" level=info msg="Row copy complete" migration=b6244fb7-7b39-48f4-a54c-d6cd83bc2d18

time="2022-03-15T11:46:52Z" level=info msg="Copy: 200/200 100.0%!;(MISSING) Applied: 0; Backlog: 0/1000; Time: 1s(total), 1s(copy); streamer: mysql-bin-changelog.000031:16949173; Lag: 0.01s, State: migrating; ETA: due" migration=b6244fb7-7b39-48f4-a54c-d6cd83bc2d18
```

FWIW, there's a much simpler way to make this change. In our fork, we added `this.migrationContext.Log.Infof(status)` [immediately after the line that prints to stdout](https://github.com/github/gh-ost/blob/master/go/logic/migrator.go#L1017).

**Comment by timvaillancourt** [comment]
@SocalNick makes sense, thanks!

I think this makes sense to merge once this PR is rebased. Currently it has conflicts that must be resolved

**Comment by SocalNick** [comment]
@timvaillancourt we've archived our fork so I reopened as #1193

I also made a very simple alternative in #1194

**Pull request closed without merging**
