### PR TITLE
Don't continue if build fails

### PR DESCRIPTION
**Pull request by dveeden**
Stop build.sh if any error pops up.

### CODE REVIEW

**Comment by SuperQ** [comment]
I usually prefer to catch errors explicitly rather than do `set -e`.  The reasoning behind this is bash doesn't give you a traceback when an error happens.  It makes failures difficult to debug.

**Comment by dveeden** [comment]
I converted build to a function and let it check the return code of `go build`. This also allows easier adding of other operating systems. I tested FreeBSD and that worked. A build on windows failed because syslog.* is not working there.

I don't think building on FreeBSD should be done by default as testing is probably only done for macOS and Linux.

**Comment by SuperQ** [comment]
Very nice. :+1:

**Comment by shlomi-noach** [comment]
Merged manually, thank you!

**Pull request closed without merging**
