### PR TITLE
Parsing ipv6 addresses

### LINKED ISSUE #604: -assume-master-host doesn't work with IPv6 literals
I can't figure out how to make `--assume-master-host` respect IPv6 addresses. Passing `--assume-master-host "some:ipv6:address"` doesn't work; neither do `--assume-master-host "[some:ipv6::address]` nor `--assume-master-host "[some:ipv6:address]:3306`. I get a `FATAL Invalid port: ipv6:address]:3306`. I'm guessing something is splitting on `:` to get a host/port instead of properly parsing addresses.

This is with version 1.0.46

### PR DESCRIPTION
**Pull request by shlomi-noach**
Fixed #604 

This PR correctly parses `ipv6` addresses. The following are valid:

- `0:0:0:0:0:0:0:0`
- `::1`
- `2001:db8:1f70::999:de8:7648:6e8`
- `[2001:db8:1f70::999:de8:7648:6e8]:3306`

cc @Roguelazer

### CODE REVIEW

**Comment by Roguelazer** [comment]
I tested this in our staging environment and it seemed to work correctly.

**Comment by shlomi-noach** [comment]
@Roguelazer thank you. It's a bit of a hack0ish solution, but it should suffice for `gh-ost`.

**Comment by Tomas2046** [comment]
#640

**Comment by timvaillancourt** [comment]
This is passing internal tests using IPV4 address, meaning I can confirm it doesn't break existing use cases

> I tested this in our staging environment and it seemed to work correctly.
Considering the IPV6 side tested by @Roguelazer here

Thanks @shlomi-noach and @Roguelazer!

**Pull request merged**
