### PR TITLE
MySQL 8.0.13: rename table

### PR DESCRIPTION
**Pull request by shlomi-noach**
Solves https://github.com/github/gh-ost/issues/714

Possibly solves #687 

This PR utilizes `8.0.13` `RENAME TABLE` which supports renaming while holding `WRITE` lock on table. This allows us to use simpler cut-over logic.

### CODE REVIEW

**Comment by peppy** [comment]
On an initial test, it gets stuck in a loop with a lock held:

```
Copy: 48290/48290 100.0%; Applied: 20; Backlog: 0/1000; Time: 25s(total), 2s(copy); streamer: mysql-bin.005479:547434959; State: migrating; ETA: due
2019-02-18 01:08:49 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`osu_apikeys` to `osu`.`_osu_apikeys_del`, `osu`.`_osu_apikeys_gho` to `osu`.`osu_apikeys`
2019-02-18 01:08:49 ERROR Error 1192: Can't execute the given command because you have active locked tables or an active transaction
Copy: 48290/48290 100.0%; Applied: 20; Backlog: 0/1000; Time: 26s(total), 2s(copy); streamer: mysql-bin.005479:548124572; State: migrating; ETA: due
2019-02-18 01:08:50 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`osu_apikeys` to `osu`.`_osu_apikeys_del`, `osu`.`_osu_apikeys_gho` to `osu`.`osu_apikeys`
2019-02-18 01:08:50 ERROR Error 1192: Can't execute the given command because you have active locked tables or an active transaction
Copy: 48290/48290 100.0%; Applied: 20; Backlog: 0/1000; Time: 27s(total), 2s(copy); streamer: mysql-bin.005479:548700427; State: migrating; ETA: due
2019-02-18 01:08:51 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`osu_apikeys` to `osu`.`_osu_apikeys_del`, `osu`.`_osu_apikeys_gho` to `osu`.`osu_apikeys`
2019-02-18 01:08:51 ERROR Error 1192: Can't execute the given command because you have active locked tables or an active transaction
Copy: 48290/48290 100.0%; Applied: 20; Backlog: 0/1000; Time: 28s(total), 2s(copy); streamer: mysql-bin.005479:548967985; State: migrating; ETA: due
2019-02-18 01:08:52 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`osu_apikeys` to `osu`.`_osu_apikeys_del`, `osu`.`_osu_apikeys_gho` to `osu`.`osu_apikeys`
2019-02-18 01:08:52 ERROR Error 1192: Can't execute the given command because you have active locked tables or an active transaction
```

**Comment by shlomi-noach** [comment]
@peppy thank you -- what is the exact MySQL version you're testing?

**Comment by peppy** [comment]
`/usr/sbin/mysqld  Ver 8.0.12 for Linux on x86_64 (MySQL Community Server - GPL)`

**Comment by ggunson** [comment]
@peppy The new RENAME TABLE behavious is from 8.0.13, so you'll need to upgrade your server first.

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-13.html
> Previously, executing RENAME TABLE required that there be no tables locked with LOCK TABLES. Now it is possible to rename tables that are locked with a WRITE lock or that are the product of renaming WRITE-locked tables from earlier steps in a multiple-table rename operation.

**Comment by peppy** [comment]
Ah, I see. I did try an upgrade a few days ago but ran into some critical issues. Will attempt again over the next couple of days.

**Comment by shlomi-noach** [comment]
Right now the code wrongly assumes that if you use `8.0` then the feature already exists. Need to fix that.

**Comment by shlomi-noach** [comment]
as per https://github.com/github/gh-ost/pull/715/files/8ce66775eded532ad23d7921665e0a8ccefafb9f..81df93dab3b9ef8f5cdf7118aa12b88dd9154b46 we now check explicitly for `8.0.13` or above before applying the new logic.

**Comment by shlomi-noach** [comment]
...which will break on MariaDB.

- [ ] exclude MariaDB > 8.0.13 from this logic.

**Comment by shlomi-noach** [comment]
@LUSTY666 can you please clarify why you approved this PR? There is recently far too many bots interfering with this repo, and your handle seems like a bot's handle.

**Comment by drogart** [comment]
I tested using dbdeployer with 8.0.13.  The cutover fails with this error:

2019-02-20 15:31:58 INFO Locking `foo`.`foo`
2019-02-20 15:31:58 INFO Table locked
2019-02-20 15:31:58 INFO Writing changelog state: AllEventsUpToLockProcessed:1550701918727020000
2019-02-20 15:31:58 INFO Intercepted changelog state AllEventsUpToLockProcessed
2019-02-20 15:31:58 INFO Handled changelog state AllEventsUpToLockProcessed
2019-02-20 15:31:58 INFO Waiting for events up to lock
Copy: 10000001/10000001 100.0%; Applied: 0; Backlog: 1/1000; Time: 1m40s(total), 1m39s(copy); streamer: mysql-bin.000003:93519165; State: migrating; ETA: due
2019-02-20 15:31:59 INFO Waiting for events up to lock: got AllEventsUpToLockProcessed:1550701918727020000
2019-02-20 15:31:59 INFO Done waiting for events up to lock; duration=1.001255032s
# Migrating `foo`.`foo`; Ghost table is `foo`.`_foo_gho`
# Migrating drogart-us-la:20314; inspecting drogart-us-la:20314; executing on drogart-us-la
# Migration started at Wed Feb 20 15:30:19 -0700 2019
# chunk-size: 1000; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: ; critical-load: ; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle 
# Serving on unix socket: /tmp/gh-ost.foo.foo.sock
Copy: 10000001/10000001 100.0%; Applied: 0; Backlog: 0/1000; Time: 1m40s(total), 1m39s(copy); streamer: mysql-bin.000003:93520871; State: migrating; ETA: due
2019-02-20 15:31:59 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `foo`.`foo` to `foo`.`_foo_del`, `foo`.`_foo_gho` to `foo`.`foo`
2019-02-20 15:31:59 ERROR Error 1100: Table '_foo_gho' was not locked with LOCK TABLES

I think the problem is that the new rename behavior in 8.0.13 requires both tables to be locked; gh-ost only locks the original table from what I see in the log.

Manual execution to show what I mean:

FAILURE (what gh-ost does now):
master [localhost] {root} (foo) > lock table foo write;
Query OK, 0 rows affected (0.00 sec)

master [localhost] {root} (foo) > rename /* gh-ost */ table `foo`.`foo` to `foo`.`_foo_del`, `foo`.`_foo_gho` to `foo`.`foo`;
ERROR 1100 (HY000): Table '_foo_gho' was not locked with LOCK TABLES

SUCCESS (locking both tables):
master [localhost] {root} (foo) > lock tables foo write, _foo_gho write;
Query OK, 0 rows affected (0.00 sec)

master [localhost] {root} (foo) > rename /* gh-ost */ table `foo`.`foo` to `foo`.`_foo_del`, `foo`.`_foo_gho` to `foo`.`foo`;
Query OK, 0 rows affected (0.09 sec)

Thanks for working on the mysql 8 issues - it's really appreciated.

-Dan

**Comment by peppy** [comment]
Just finished updating infrastructure to mysql 8.0.15. Can confirm @drogart's issue:

```
; State: migrating; ETA: due
2019-02-21 02:37:34 INFO Waiting for events up to lock: got AllEventsUpToLockProcessed:1550716653545707132
2019-02-21 02:37:34 INFO Done waiting for events up to lock; duration=999.005648ms
# Migrating `osu`.`phpbb_disallow`; Ghost table is `osu`.`_phpbb_disallow_gho`
# Migrating db-master:3306; inspecting db-master:3306; executing on db-master
# Migration started at Thu Feb 21 02:37:32 +0000 2019
# chunk-size: 1000; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: Threads_running=25; critical-load: Threads_running=1000; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# throttle-control-replicas count: 1
# panic-flag-file: /tmp/ghost.panic.flag
# Serving on unix socket: /tmp/gh-ost.osu.phpbb_disallow.sock
Copy: 103/103 100.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 1s(copy); streamer: mysql-bin.005597:170648058; State: migrating; ETA: due
2019-02-21 02:37:34 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`phpbb_disallow` to `osu`.`_phpbb_disallow_del`, `osu`.`_phpbb_disallow_gho` to `osu`.`phpbb_disallow`
2019-02-21 02:37:34 ERROR Error 1100: Table '_phpbb_disallow_gho' was not locked with LOCK TABLES
Copy: 103/103 100.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 1s(copy); streamer: mysql-bin.005597:170966629; State: migrating; ETA: due
2019-02-21 02:37:35 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`phpbb_disallow` to `osu`.`_phpbb_disallow_del`, `osu`.`_phpbb_disallow_gho` to `osu`.`phpbb_disallow`
2019-02-21 02:37:35 ERROR Error 1100: Table '_phpbb_disallow_gho' was not locked with LOCK TABLES
Copy: 103/103 100.0%; Applied: 0; Backlog: 0/1000; Time: 4s(total), 1s(copy); streamer: mysql-bin.005597:171189915; State: migrating; ETA: due
2019-02-21 02:37:36 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`phpbb_disallow` to `osu`.`_phpbb_disallow_del`, `osu`.`_phpbb_disallow_gho` to `osu`.`phpbb_disallow`
2019-02-21 02:37:36 ERROR Error 1100: Table '_phpbb_disallow_gho' was not locked with LOCK TABLES
Copy: 103/103 100.0%; Applied: 0; Backlog: 0/1000; Time: 5s(total), 1s(copy); streamer: mysql-bin.005597:171418721; State: migrating; ETA: due
2019-02-21 02:37:37 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`phpbb_disallow` to `osu`.`_phpbb_disallow_del`, `osu`.`_phpbb_disallow_gho` to `osu`.`phpbb_disallow`
2019-02-21 02:37:37 ERROR Error 1100: Table '_phpbb_disallow_gho' was not locked with LOCK TABLES
Copy: 103/103 100.0%; Applied: 0; Backlog: 0/1000; Time: 6s(total), 1s(copy); streamer: mysql-bin.005597:171686576; State: migrating; ETA: due
2019-02-21 02:37:38 INFO Issuing and expecting this to succeed: rename /* gh-ost */ table `osu`.`phpbb_disallow` to `osu`.`_phpbb_disallow_del`, `osu`.`_phpbb_disallow_gho` to `osu`.`phpbb_disallow`
2019-02-21 02:37:38 ERROR Error 1100: Table '_phpbb_disallow_gho' was not locked with LOCK TABLES
```

**Comment by shlomi-noach** [comment]
> I think the problem is that the new rename behavior in 8.0.13 requires both tables to be locked

This complicates matters. I can't just place a lock on both tables, since I want to be able to keep writing to the _ghost_ table what remains in the binary logs after having locked the original table. The only way to be able to do so is if the same connection which places the lock would be the one to apply the remaining events; this is doable but non trivial.

I don't expect to solve this immediately.

**Comment by peppy** [comment]
Thanks for the update and information. Wish I had the resources to help with more than just testing.

**Comment by shlomi-noach** [comment]
OK, so I'm not sure this PR is necessary, and `master` branch actually works on MySQL `8.0.16` and `8.0.18` (maybe on other versions, too, but those are the ones I tested).

I previously reported on https://github.com/github/gh-ost/issues/687#issuecomment-581923115, which is not the correct place.

Testing `8.0.18`:



I issued:
```
gh-ost \
  --user=gh-ost \
  --password=gh-ost \
  --host=localhost \
  --port=20821 \
  --assume-master-host=localhost:20819 \
  --database=test \
  --table=gh_ost_test \
  --alter='engine=innodb' \
  --exact-rowcount \
  --assume-rbr \
  --initially-drop-old-table \
  --initially-drop-ghost-table \
  --throttle-query='select timestampdiff(second, min(last_update), now()) < 5 from _gh_ost_test_ghc' \
  --serve-socket-file=/tmp/gh-ost.test.sock \
  --initially-drop-socket-file \
  --default-retries=3 \
  --chunk-size=10 \
  --verbose \
  --debug \
  --stack \
  --execute
```
I got:
```
2020-02-04 15:59:56 INFO starting gh-ost
2020-02-04 15:59:56 INFO Migrating `test`.`gh_ost_test`
2020-02-04 15:59:56 INFO connection validated on localhost:20821
2020-02-04 15:59:56 INFO User has SUPER, REPLICATION SLAVE privileges, and has ALL privileges on `test`.*
2020-02-04 15:59:56 INFO binary logs validated on localhost:20821
2020-02-04 15:59:56 INFO Inspector initiated on shlomi-oct:20821, version 8.0.18
2020-02-04 15:59:56 INFO Table found. Engine=InnoDB
2020-02-04 15:59:56 DEBUG Estimated number of rows via STATUS: 3
2020-02-04 15:59:56 DEBUG Validated no foreign keys exist on table
2020-02-04 15:59:56 DEBUG Validated no triggers exist on table
2020-02-04 15:59:56 INFO Estimated number of rows via EXPLAIN: 3
2020-02-04 15:59:56 DEBUG Potential unique keys in gh_ost_test: [PRIMARY (auto_increment): [id]; has nullable: false]
2020-02-04 15:59:56 INFO Master forced to be localhost:20819
2020-02-04 15:59:56 INFO log_slave_updates validated on localhost:20821
2020-02-04 15:59:56 INFO connection validated on localhost:20821
2020-02-04 15:59:56 DEBUG Streamer binlog coordinates: mysql-bin.000001:203020
2020-02-04 15:59:56 INFO Connecting binlog streamer at mysql-bin.000001:203020
[2020/02/04 15:59:56] [info] binlogsyncer.go:133 create BinlogSyncer with config {99999 mysql localhost 20821 gh-ost    false false <nil> false UTC true 0 0s 0s 0 false}
[2020/02/04 15:59:56] [info] binlogsyncer.go:354 begin to sync binlog from position (mysql-bin.000001, 203020)
[2020/02/04 15:59:56] [info] binlogsyncer.go:203 register slave for master server localhost:20821
2020-02-04 15:59:56 DEBUG Beginning streaming
[2020/02/04 15:59:56] [info] binlogsyncer.go:723 rotate to (mysql-bin.000001, 203020)
2020-02-04 15:59:56 INFO rotate to next log from mysql-bin.000001:0 to mysql-bin.000001
2020-02-04 15:59:56 INFO connection validated on localhost:20819
2020-02-04 15:59:56 INFO connection validated on localhost:20819
2020-02-04 15:59:56 INFO will use time_zone='SYSTEM' on applier
2020-02-04 15:59:56 INFO Examining table structure on applier
2020-02-04 15:59:56 INFO Applier initiated on shlomi-oct:20819, version 8.0.18
2020-02-04 15:59:56 INFO Dropping table `test`.`_gh_ost_test_gho`
2020-02-04 15:59:56 INFO Table dropped
2020-02-04 15:59:56 INFO Dropping table `test`.`_gh_ost_test_del`
2020-02-04 15:59:56 INFO Table dropped
2020-02-04 15:59:56 INFO Dropping table `test`.`_gh_ost_test_ghc`
2020-02-04 15:59:56 INFO Table dropped
2020-02-04 15:59:56 INFO Creating changelog table `test`.`_gh_ost_test_ghc`
2020-02-04 15:59:56 INFO Changelog table created
2020-02-04 15:59:56 INFO Creating ghost table `test`.`_gh_ost_test_gho`
2020-02-04 15:59:56 INFO Ghost table created
2020-02-04 15:59:56 INFO Altering ghost table `test`.`_gh_ost_test_gho`
2020-02-04 15:59:56 DEBUG ALTER statement: alter /* gh-ost */ table `test`.`_gh_ost_test_gho` drop column shushu, engine=innodb
2020-02-04 15:59:56 INFO Ghost table altered
2020-02-04 15:59:56 INFO Waiting for ghost table to be migrated. Current lag is 0s
2020-02-04 15:59:56 INFO Intercepted changelog state GhostTableMigrated
2020-02-04 15:59:56 INFO Handled changelog state GhostTableMigrated
2020-02-04 15:59:56 DEBUG ghost table migrated
2020-02-04 15:59:56 DEBUG Potential unique keys in _gh_ost_test_gho: [PRIMARY (auto_increment): [id]; has nullable: false]
2020-02-04 15:59:56 INFO Chosen shared unique key is PRIMARY
2020-02-04 15:59:56 INFO Shared columns are id,i,color
2020-02-04 15:59:56 INFO Listening on unix socket file: /tmp/gh-ost.test.sock
2020-02-04 15:59:56 INFO As instructed, counting rows in the background; meanwhile I will use an estimated count, and will update it later on
2020-02-04 15:59:56 DEBUG Reading migration range according to key: PRIMARY
2020-02-04 15:59:56 INFO As instructed, I'm issuing a SELECT COUNT(*) on the table. This may take a while
2020-02-04 15:59:56 INFO Migration min values: [1]
2020-02-04 15:59:56 DEBUG Reading migration range according to key: PRIMARY
2020-02-04 15:59:56 INFO Migration max values: [3]
2020-02-04 15:59:56 INFO Waiting for first throttle metrics to be collected
2020-02-04 15:59:56 INFO First throttle metrics collected
2020-02-04 15:59:56 DEBUG Operating until row copy is complete
# Migrating `test`.`gh_ost_test`; Ghost table is `test`.`_gh_ost_test_gho`
2020-02-04 15:59:56 DEBUG Getting nothing in the write queue. Sleeping...
# Migrating shlomi-oct:20819; inspecting shlomi-oct:20821; executing on shlomi-oct
# Migration started at Tue Feb 04 15:59:56 +0200 2020
# chunk-size: 100; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: ; critical-load: ; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# throttle-query: select timestampdiff(second, min(last_update), now()) < 5 from _gh_ost_test_ghc
# Serving on unix socket: /tmp/gh-ost.test.sock
Copy: 0/3 0.0%; Applied: 0; Backlog: 0/1000; Time: 0s(total), 0s(copy); streamer: mysql-bin.000001:206450; Lag: 0.02s, State: throttled, throttle-query; ETA: N/A
Copy: 0/3 0.0%; Applied: 0; Backlog: 0/1000; Time: 1s(total), 1s(copy); streamer: mysql-bin.000001:211052; Lag: 0.01s, State: throttled, throttle-query; ETA: N/A
Copy: 0/3 0.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 2s(copy); streamer: mysql-bin.000001:215654; Lag: 0.02s, State: throttled, throttle-query; ETA: N/A
Copy: 0/3 0.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 3s(copy); streamer: mysql-bin.000001:220252; Lag: 0.02s, State: throttled, throttle-query; ETA: N/A
Copy: 0/3 0.0%; Applied: 0; Backlog: 0/1000; Time: 4s(total), 4s(copy); streamer: mysql-bin.000001:224852; Lag: 0.01s, State: throttled, throttle-query; ETA: N/A
Copy: 0/3 0.0%; Applied: 0; Backlog: 0/1000; Time: 5s(total), 5s(copy); streamer: mysql-bin.000001:229452; Lag: 0.02s, State: throttled, throttle-query; ETA: N/A
2020-02-04 16:00:01 DEBUG Issued INSERT on range: [1]..[3]; iteration: 0; chunk-size: 100
2020-02-04 16:00:01 DEBUG Iteration complete: no further range to iterate
2020-02-04 16:00:01 DEBUG Getting nothing in the write queue. Sleeping...
2020-02-04 16:00:01 INFO Row copy complete
Copy: 3/3 100.0%; Applied: 0; Backlog: 0/1000; Time: 5s(total), 5s(copy); streamer: mysql-bin.000001:231913; Lag: 0.01s, State: migrating; ETA: due
2020-02-04 16:00:01 DEBUG checking for cut-over postpone
2020-02-04 16:00:01 DEBUG checking for cut-over postpone: complete
2020-02-04 16:00:01 INFO Grabbing voluntary lock: gh-ost.51.lock
2020-02-04 16:00:01 INFO Setting LOCK timeout as 6 seconds
2020-02-04 16:00:01 INFO Looking for magic cut-over table
2020-02-04 16:00:01 INFO Creating magic cut-over table `test`.`_gh_ost_test_del`
2020-02-04 16:00:01 INFO Magic cut-over table created
2020-02-04 16:00:01 INFO Locking `test`.`gh_ost_test`, `test`.`_gh_ost_test_del`
2020-02-04 16:00:01 INFO Tables locked
2020-02-04 16:00:01 INFO Session locking original & magic tables is 51
2020-02-04 16:00:01 INFO Writing changelog state: AllEventsUpToLockProcessed:1580824801554808000
2020-02-04 16:00:01 INFO Waiting for events up to lock
2020-02-04 16:00:01 INFO Intercepted changelog state AllEventsUpToLockProcessed
2020-02-04 16:00:01 INFO Handled changelog state AllEventsUpToLockProcessed
Copy: 3/3 100.0%; Applied: 0; Backlog: 1/1000; Time: 6s(total), 5s(copy); streamer: mysql-bin.000001:236706; Lag: 0.02s, State: migrating; ETA: due
2020-02-04 16:00:02 DEBUG Getting nothing in the write queue. Sleeping...
2020-02-04 16:00:02 INFO Waiting for events up to lock: got AllEventsUpToLockProcessed:1580824801554808000
2020-02-04 16:00:02 INFO Done waiting for events up to lock; duration=989.170997ms
# Migrating `test`.`gh_ost_test`; Ghost table is `test`.`_gh_ost_test_gho`
# Migrating shlomi-oct:20819; inspecting shlomi-oct:20821; executing on shlomi-oct
# Migration started at Tue Feb 04 15:59:56 +0200 2020
# chunk-size: 100; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: ; critical-load: ; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# throttle-query: select timestampdiff(second, min(last_update), now()) < 5 from _gh_ost_test_ghc
# Serving on unix socket: /tmp/gh-ost.test.sock
Copy: 3/3 100.0%; Applied: 0; Backlog: 0/1000; Time: 6s(total), 5s(copy); streamer: mysql-bin.000001:238424; Lag: 0.02s, State: migrating; ETA: due
2020-02-04 16:00:02 INFO Setting RENAME timeout as 3 seconds
2020-02-04 16:00:02 INFO Session renaming tables is 53
2020-02-04 16:00:02 INFO Issuing and expecting this to block: rename /* gh-ost */ table `test`.`gh_ost_test` to `test`.`_gh_ost_test_del`, `test`.`_gh_ost_test_gho` to `test`.`gh_ost_test`
2020-02-04 16:00:02 INFO Found atomic RENAME to be blocking, as expected. Double checking the lock is still in place (though I don't strictly have to)
2020-02-04 16:00:02 INFO Checking session lock: gh-ost.51.lock
2020-02-04 16:00:02 INFO Connection holding lock on original table still exists
2020-02-04 16:00:02 INFO Will now proceed to drop magic table and unlock tables
2020-02-04 16:00:02 INFO Dropping magic cut-over table
2020-02-04 16:00:02 INFO Releasing lock from `test`.`gh_ost_test`, `test`.`_gh_ost_test_del`
2020-02-04 16:00:02 INFO Tables unlocked
2020-02-04 16:00:02 INFO Tables renamed
2020-02-04 16:00:02 INFO Lock & rename duration: 1.006560267s. During this time, queries on `gh_ost_test` were blocked
2020-02-04 16:00:02 INFO Looking for magic cut-over table
[2020/02/04 16:00:02] [info] binlogsyncer.go:164 syncer is closing...
2020-02-04 16:00:02 DEBUG done streaming events
2020-02-04 16:00:02 DEBUG Done streaming
[2020/02/04 16:00:02] [error] binlogstreamer.go:77 close sync with err: sync is been closing...
2020-02-04 16:00:02 INFO Closed streamer connection. err=<nil>
[2020/02/04 16:00:02] [info] binlogsyncer.go:179 syncer is closed
2020-02-04 16:00:02 INFO Dropping table `test`.`_gh_ost_test_ghc`
2020-02-04 16:00:02 INFO Table dropped
2020-02-04 16:00:02 INFO Am not dropping old table because I want this operation to be as live as possible. If you insist I should do it, please add `--ok-to-drop-table` next time. But I prefer you do not. To drop the old table, issue:
2020-02-04 16:00:02 INFO -- drop table `test`.`_gh_ost_test_del`
2020-02-04 16:00:02 INFO Done migrating `test`.`gh_ost_test`
2020-02-04 16:00:02 INFO Removing socket file: /tmp/gh-ost.test.sock
2020-02-04 16:00:02 INFO Tearing down inspector
2020-02-04 16:00:02 INFO Tearing down applier
2020-02-04 16:00:02 DEBUG Tearing down...
2020-02-04 16:00:02 INFO Tearing down streamer
2020-02-04 16:00:02 INFO Tearing down throttler
2020-02-04 16:00:02 DEBUG Tearing down...
# Done
```

**Comment by peppy** [comment]
Can confirm that this seems to no longer be required.

**Comment by shlomi-noach** [comment]
According to my tests `gh-ost` supports MySQL `8.0.16` and `8.0.18`, so I'm closing this issue.

**Pull request closed without merging**
