### PR TITLE
Generated column as part of UNIQUE (or PRIMARY) KEY

### PR DESCRIPTION
**Pull request by shlomi-noach**
Resubmission of https://github.com/openark/gh-ost/pull/13 from downstream.

Supporting the case where any unique key, and in particular the `PRIMARY KEY`, includes a `GENERATED` column.

A user with a large database deployment, who initially reported the issue, has confirmed the fix works as expected.
 
- [x] contributed code is using same conventions as original code
- [x] `script/cibuild` returns with no formatting errors, build errors or unit test errors.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
At this time this PR appears to contain many more commits than actually changed; this is because there's still other outstanding requests to merge upstream. For reference, the specific changes to this PR are https://github.com/openark/gh-ost/pull/13/files

**Review by timvaillancourt — APPROVED** [review]
Thanks @shlomi-noach 👍

**Comment by timvaillancourt** [comment]
@shlomi-noach 👋 this is being tested now!

Could you re-base this branch so it's ready to merge after a few days of testing? 🙇

**Comment by shlomi-noach** [comment]
Rebased!

**Comment by timvaillancourt** [comment]
Thanks @shlomi-noach this passed tests for over a week. Merging 👍

**Pull request merged**
