### PR TITLE
Improved connection type logging

### LINKED ISSUE #461: Improve connection logging to indicate the usage.
I have been testing gh-ost and notice it may make several different types of connections to different servers. That may lead to confusion if you have a lot. Therefore I think it would be good to identify: the "writer" connection, the "reader" (when you're running against a replica) and even the "monitoring" connections.

e.g.
```
2017-07-26 11:02:40 INFO connection validated on myreplica.example.com:3306
```
maybe could be:

```
2017-07-26 11:02:40 INFO inspector connection validated on myreplica.example.com:3306
```
(or similar)

and similarly adjust the entries for the connections used for writing and any other read handles you make.

### PR DESCRIPTION
**Pull request by akshaychhajed**
## A Pull Request should be associated with an Issue.

> We wish to have discussions in Issues. A single issue may be targeted by multiple PRs.
> If you're offering a new feature or fixing anything, we'd like to know beforehand in Issues,
> and potentially we'll be able to point development in a particular direction.

Related issue: https://github.com/github/gh-ost/issues/461

> Further notes in https://github.com/github/gh-ost/blob/master/.github/CONTRIBUTING.md
> Thank you! We are open to PRs, but please understand if for technical reasons we are unable to accept each and any PR

### Description

This PR adds connection type to logs. It helps distinguish connection type (inspector, streamer and applier)
Fixes #461 
> In case this PR introduced Go code changes:

- [x] contributed code is using same conventions as original code
- [x] `script/cibuild` returns with no formatting errors, build errors or unit test errors.

### CODE REVIEW

**Comment by timvaillancourt** [comment]
@akshaychhajed thanks for your contribution and sorry for the delay

Could you resolve the merge conflicts with this PR above? I can test and merge this PR once the changes are up-to-date

**Comment by akshaychhajed** [comment]
@timvaillancourt looks like I am little late for this. Let me know if I can help.

**Review by timvaillancourt — APPROVED** [review]
LGTM

**Comment by timvaillancourt** [comment]
> @timvaillancourt looks like I am little late for this. Let me know if I can help.

@akshaychhajed I've fixed the merge conflicts and this change LGTM 👍. Thanks!

**Pull request merged**
