### PR TITLE
testing 5.7 and JSON

### PR DESCRIPTION
**Pull request by shlomi-noach**
This PR runs localtests on `5.7`. It also adds `JSON` datatype tests.

### CODE REVIEW

**Comment by arthurnn** [comment]
How do we run the localtests?
Just run the test.sh script?
Also, do they run on ci?

**Comment by shlomi-noach** [comment]
So `localtests` are not yet running from CI, unfortunately, and there's a measure of a manual setup to make them work.

See https://github.com/github/gh-ost/pull/427 for a contributor's work to make that run on CI. I think, however, that work on this has stopped seeing that the PR is stale. Also see discussion on https://github.com/github/gh-ost/issues/425

TL;DR you need a local master/replica setup, with your own implementation for `gh-ost-test-mysql-master` and `gh-ost-test-mysql-replica`.

Another consideration is that, at least up till now, I ran these tests on `5.6`. We might want to run all tests on `5.6` AND `5.7` AND whatever else.

**Comment by arthurnn** [comment]
I will take a look.

On LHM, we had a few scripts to setup the master-replica for tests https://github.com/soundcloud/lhm/blob/master/bin/lhm-spec-setup-cluster.sh , but we also didn't run that on CI

**Comment by shlomi-noach** [comment]
Hmm messed this branch up ; continued elsewhere.

**Pull request merged**
