### PR TITLE
added charset support & tests

### PR DESCRIPTION
**Pull request by shlomi-noach**
Storyline: https://github.com/github/gh-ost/issues/226

This adds tests for `utf8` and `latin1` text columns with "special" characters

### CODE REVIEW

**Comment by SuperQ** [comment]
Don't forget to test utf8mb4 with some emoji chars. :smile: :hankey: :pizza:

**Comment by shlomi-noach** [comment]
true, true. Bummed by the `latin1` problem at the moment.

**Comment by SuperQ** [comment]
Yup, char encoding is a long sad MySQL story :disappointed: :sob: :crying_cat_face:

**Comment by shlomi-noach** [comment]
`utf8mb4` is good (rather, made it good easily, need to merge).
`latin1` still a pain.

**Comment by shlomi-noach** [comment]
The problem goes away when the MySQL connection is configured to use `charset=latin1`. But this is not a valid solution because we wish to support tables that have multiple charset columns. Maybe as a quick workaround...

**Comment by shlomi-noach** [comment]
Character set recognition and manipulation

- Identifying textual characters sets; converting into specific type when applying dml events
- Refactored `ColumnsList`: introducing `Column` type
- Refactored `unsigned` handling, as part of `Column`
- `Column` type supports `convertArg()`: converting value of argument according to column data type
- DB URI attempts `utf8mb4,utf8,latin1` charsets in that order (first one to be recognized wins)
- Local tests filter by pattern
- Local tests append table schema on failure
- Local tests do not have postpone flag file
- Added character set local tests: `utf8`, `utf8mb4`, `latin1`

**Comment by SuperQ** [comment]
:+1: :cake: :ice_cream:

**Comment by shlomi-noach** [comment]
all tests pass. merging.

**Pull request merged**
