### PR TITLE
Add http server for pprof

### PR DESCRIPTION
**Pull request by timvaillancourt**
### Description

In order to understand a performance issue with the inspector, this PR adds an http server to support [pprof profiling](https://golang.org/pkg/net/http/pprof/) of `gh-ost`

This is disabled by default and enabled by passing `--http-listen-addr 10.11.12.13:8080`

Endpoints:
- `GET /_ping` - returns `OK`
- `GET /debug/pprof` - returns [pprof profile data](https://golang.org/pkg/net/http/pprof/)

cc @shlomi-noach for any style thoughts

> In case this PR introduced Go code changes:

- [ ] contributed code is using same conventions as original code
- [x] `script/cibuild` returns with no formatting errors, build errors or unit test errors.

### CODE REVIEW

**Comment by rashiq** [comment]
@timvaillancourt don't see the implementation of `GET /debug/pprof` - is that still wip?

**Comment by timvaillancourt** [comment]
@rashiq that endpoint is auto-exported by `net/http/pprof`: https://golang.org/pkg/net/http/pprof/#pkg-overview

**Review by rashiq — APPROVED** [review]

**Comment by rashiq** [comment]
@timvaillancourt ah gotcha!

**Comment by timvaillancourt** [comment]
I think I might move the server funcs under `migrationContext` so the server has access to that state in the future. Any thoughts on that @shlomi-noach?

**Comment by timvaillancourt** [comment]
Closing as no longer required

**Pull request closed without merging**
