### PR TITLE
Rejecting RENAME TO|AS

### PR DESCRIPTION
**Pull request by shlomi-noach**
Closes https://github.com/github/gh-ost/issues/576

This PR rejects an alter statement of the form `RENAME TO something_else` or `RENAME AS something_else`.

`RENAME` should not be executed with `gh-ost`. It is both wastefull as well as outside the scope of `gh-ost`.

cc @rudy-gao, @zmoazeni

### CODE REVIEW

**Comment by bbuchalter** [comment]
Perhaps an addition to the limitations section of the docs? https://github.com/github/gh-ost/blob/master/doc/requirements-and-limitations.md#limitations

**Comment by shlomi-noach** [comment]
> Perhaps an addition to the limitations section of the docs?

done, thank you. Best is to add a PR review!

**Comment by bbuchalter** [comment]
> Best is to add a PR review

I'm new to this community (just joined Shopify's datastores team) so I felt most comfortable leaving a simple comment, but next time, I'll do just that. Thanks!

**Comment by davidlwpblo** [comment]
> > Best is to add a PR review
> 
> I'm new to this community (just joined Shopify's datastores team) so I felt most comfortable leaving a simple comment, but next time, I'll do just that. Thanks!

Thank you so much you know what's so crazy my personal space and property so when it come to being hacked and bullied and stuff like that I take it very personal and serious so I don't even know if anything really got done or if it was just a hoax to shut me up because I'm disabled and I supposed to be crazy you know and black lives do matter you have a blessed one

**Comment by shlomi-noach** [comment]
Spammy user reported.

**Pull request merged**
