### PR TITLE
updated go-mysql library

### PR DESCRIPTION
**Pull request by shlomi-noach**
Periodic update of the `go-mysql` library. Among other things, tackling https://github.com/github/gh-ost/issues/496

### CODE REVIEW

**Comment by shlomi-noach** [comment]
This one is failing local tests in the meantime.

**Comment by shlomi-noach** [comment]
There's an inconsistency of timzone handling between `time2` and `datetime2`, and `gh-ost` is unable to treat the two in the same way. For now, I'm not updating the `go-mysql` library.

**Comment by druud62** [comment]
In MySQL, the timestamp-type is physically stored as a UNIX-epoch-based numeric value,
but the datetime-type is much like a string. (And there is still no datetimezone-type.)

So datetime-values should always be copied as-is, as they have no inherent timezone.

This of course makes alters that switch between these types problematic, 
for example because a datetime-value can be non-existent in the current timezone.
https://bugs.mysql.com/bug.php?id=85641
And much more so if not all involved database servers run with the same timezone config.

With timestamp-values, one should simply always copy the raw UNIX-epoch-based numerical value, but there is no good functionality for that on the SQL-level.

**Comment by shlomi-noach** [comment]
> In MySQL, the timestamp-type is physically stored as a UNIX-epoch-based numeric value,
but the datetime-type is much like a string. (And there is still no datetimezone-type.)

> So datetime-values should always be copied as-is, as they have no inherent timezone.

I am indeed very much aware of both. Interestingly, B.com delivered the first non trivial TZ use case where the two did not agree with each other.

Also of interest is that binary logs always store timestamps as UTC, so they convert them, while `datetime`s are of course never converted.
This is also much about the library I use to read events from the binary logs.

**Comment by druud** [comment]
There is an exception on the "with timestamp-values, one should simply always copy the raw UNIX-epoch-based numerical value", because 0 is a special value, that should not be adjusted per timezone.

**Comment by shlomi-noach** [comment]
`go-mysql` has been updated in https://github.com/github/gh-ost/pull/684. This PR is redundant.

**Pull request closed without merging**
