### PR TITLE
Support virtual columns

### PR DESCRIPTION
**Pull request by dveeden**
### Description

Don't try to insert on virtual columns when copying rows.
I only did a very basic test, so maybe run this through some more testing?
- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `bash build.sh`

Related Issue: https://github.com/github/gh-ost/issues/138

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Yes, this will be a bit lengthier to handle; we may eventually also need to consider what happens when the alter statement changes a generated column into a non generated column. I need to wrap my head around this, but this sounds non-trivial.

**Comment by shlomi-noach** [comment]
Any thoughts on possible scenarios is appreciated!

**Comment by mizioumt** [comment]
This should work I think:

* do not INSERT into any generated column
* if a column is changed from generated to non-generated (much better done by DROP COLUMN/ADD COLUMN), then the resulting column should be treated as a new one, that is we do not INSERT to it.

So, if column `x` exists as a generated column in either old or new table, we do not insert into it.

There is an exception, though: ALTER drops a generated column `g` and also renames existing column `c` to `g`.

**Comment by shlomi-noach** [comment]
> There is an exception, though: ALTER drops a generated column g and also renames existing column c to g. 

this kind of complication can happen with normal columns as well; and it is a perfectly good way to shoot one's own foot. I'm not very concerned about that one.

> if a column is changed from generated to non-generated (much better done by DROP COLUMN/ADD COLUMN), then the resulting column should be treated as a new one, that is we do not INSERT to it.

What is the reasoning for not inserting to it?

**Comment by mizioumt** [comment]
well maybe I was wrong here the value of the original column should be INSERTed into the new one in the spirit of CHANGE/MODIFY as opposed to ADD/DROP. 
For the columns that end up virtual in the new table, DEFAULT should be inserted which is allowed, or they should not be in the list of columns in the INSERT.

**Comment by artemy-osipov** [comment]
@shlomi-noach, it would be nice to add only support for tables with virtual columns ignoring insert on such columns while changing virtual columns can be implemented in another time/PR. For now we can just forbid changing virtual columns.

**Comment by shlomi-noach** [comment]
_Finally_ getting to it. Since this PR is so old and has many conflicts, and seeing that I implemented it slightly differently, I resubmitted as https://github.com/github/gh-ost/pull/595, using parts of @dveeden 's contributions.

**Comment by shlomi-noach** [comment]
I'm closing this PR in favor of #595

**Pull request closed without merging**
