### PR TITLE
implement a logging interface

### PR DESCRIPTION
**Pull request by abeyum**
### Description
Related issue: #786 

This PR allows developers to write gh-ost logs to where they see fit by extending an interface instead of relying on the default outbrain logs.

cc: @shlomi-noach

### CODE REVIEW

**Comment by abeyum** [comment]
@shlomi-noach I noticed you've taken some action to update this pull request, looks like it has passed all the checks. Can we merge this pull request?

**Comment by shlomi-noach** [comment]
👋 @abeyum indeed I did. I'm rotating between a few issues/PRs. I apologize, but I'm still going to push this a bit, and would only be able to look into it again after end of year. I appreciate your PR and the time you took to write it.

**Comment by abeyum** [comment]
Hello @shlomi-noach,

Any chance you are free to take a look and merge? PR has passed all checks and there are no merge conflicts.

**Comment by tomkrouper** [comment]
ping @jfudally. Is this something you can look at?

**Comment by shlomi-noach** [comment]
Hi there. I'm responding because I was @-mentioned directly. I no longer work at GitHub, am no longer an owner of this repository, and am actually not working right now. I'm taking a personal break from `gh-ost` for a while, and will probably return to work on `gh-ost` at some point in the future. I'm sorry I couldn't push this through earlier.

**Comment by abeyum** [comment]
@jfudally Any chance we can review and merge this soon?

**Comment by jfudally** [comment]
@abeyum Thank you for the submission, I appreciate the work you put into this.  Sorry it's taken so long to get this in!

**Pull request merged**
