### PR TITLE
Gbk encoding simple

### PR DESCRIPTION
**Pull request by shlomi-noach**
Context: https://github.com/github/gh-ost/issues/532, see also https://github.com/github/gh-ost/pull/559

Some time after #533 was submitted by @ceshihao we [found](https://github.com/github/gh-ost/pull/533#issuecomment-371382744) that `gkb` charset seems to work without specifying risky-charset argument. This PR is a stripped down version of #533 in an attempt to find the minimal set of changes where `gbk` is still supported.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Interestingly tests pass even though we use `interpolateParams=true`:

https://github.com/github/gh-ost/blob/12424e94fb2cffceefb44f9d3ab20c2266a1ef2b/vendor/github.com/go-sql-driver/mysql/utils.go#L149-L151

Seems like as long as not specified via DSN, `gbk` is good to go.

**Comment by ceshihao** [comment]
@shlomi-noach 

I think it is because `gh-ost` DSN only contains `interpolateParams ` and `charset`, but NOT `collation`.

From the code you linked, the validation is on `interpolateParams ` and `collation`.

**Comment by shlomi-noach** [comment]
@ceshihao makes sense. Can you possibly test this branch on your side and confirm it works as expected?

**Comment by ceshihao** [comment]
@shlomi-noach It works on my side.

BTW
I think this change is not needed either.

https://github.com/github/gh-ost/pull/560/files#diff-0ec6a3deacd5e2577724a82d8347226fR59

**Comment by shlomi-noach** [comment]
Great, thank you for testing! And thank you for your efforts.

> BTW I think this change is not needed either.

Yep. I thought I might leave that as a strict reminder about `interpolateParams`.

**Pull request merged**
