### PR TITLE
All MySQL DBs limited to max 3 concurrent/idle connections #15

### PR DESCRIPTION
**Pull request by shlomi-noach**
Resubmission of https://github.com/openark/gh-ost/pull/15 from downstream.

Issue reported privately by community user. In some scenario (user had semi-sync + long row data) `gh-ost` connections piled up to `MAX_USER_CONNECTIONS`. This PR puts a hard limit (constant `3`) on all pools. There's several of those (inspector, applier, throttler, and more), but each is limited to to 3 connections which at least does not cause a connection pileup on the MySQL server(s).

- [x] contributed code is using same conventions as original code
- [x] `script/cibuild` returns with no formatting errors, build errors or unit test errors.

### CODE REVIEW

**Comment by timvaillancourt** [comment]
@shlomi-noach 👋 that's a good idea, thanks for the PR 👍 

I'm seeing potentially unrelated changes vs https://github.com/openark/gh-ost/pull/15 in this PR. Can you confirm?

**Comment by shlomi-noach** [comment]
> I'm seeing potentially unrelated changes vs openark#15 in this PR. Can you confirm?

@timvaillancourt yeah, that's due to #911 and #919 not merged yet, I've continued on top of these. I can sanitize the relevant changes to this PR and re-submit (but hoping it would only be a matter of tim etill #911 and #919 are merged).

**Comment by timvaillancourt** [comment]
> > I'm seeing potentially unrelated changes vs [openark#15](https://github.com/openark/gh-ost/pull/15) in this PR. Can you confirm?
> 
> @timvaillancourt yeah, that's due to #911 and #919 not merged yet, I've continued on top of these. I can sanitize the relevant changes to this PR and re-submit (but hoping it would only be a matter of tim etill #911 and #919 are merged).

@shlomi-noach ahh thanks. No problem, I can merge those PRs together eventually 👍

**Review by timvaillancourt — APPROVED** [review]

**Comment by shlomi-noach** [comment]
branch updated after recent merge of downstream contribution.

**Comment by timvaillancourt** [comment]
This low-risk changed has passed many tests, merging it 👍 

Thanks @shlomi-noach 🎉

**Pull request merged**
